---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}othereureka.credentials.uri:http://${PREFIX:}othereureka.${application.domain:cfapps.io}}/eureka/

---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
